name: Test

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install system dependencies
              run: sudo apt-get install -y libasound2 libudev-dev 

            - name: Cache dependencies
              uses: actions/cache@v2
              with: 
                path: |
                  target
                  ~/.cargo
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Update dependencies
              run: cargo fetch

            - name: Check formatting
              run: cargo fmt --check

            - name: Check Clippy
              run: cargo clippy --all --all-features -- -D warnings

            - name: Build crate
              run: cargo build --all --all-features

            - name: Run tests
              run: cargo test --all --all-features